### PR TITLE
Added listtasks command to list open tasks for a user

### PR DESCRIPTION
**Pull request by mitali31**
'listtasks' command has the following properties:

1. Takes Phabricator username as input and displays the currently open tasks for that user. 
2. If no username is provided, their Slack username is used to look up tasks (assumption being that their Slack username matches their Phabricator username). 
3. If username is not found, an error message is displayed.

### CODE REVIEW

**Comment by schemar** [comment]
@mitali31 first of all sorry that no one replied to you for so long!
Is this PR still relevant? If so can you please rebase on the latest `master`?
Thanks!

**Comment by mitali31** [comment]
Yep, it's still relevant.

**Comment by schemar** [comment]
Thank you @mitali31! Something went wrong when you rebased, so that the changes from `master` are now listed in the diff. Can you please re-create the PR so that only your changes are listed?

Furthermore, can you please add tests so that your code is covered at least up to the specified target? That would be very nice.

Thank you!

**Comment by mitali31** [comment]
Sounds good. I'll close this and put up a new PR.

Thanks!

**Comment by schemar** [comment]
Thank you!

**Pull request closed without merging**
